<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPhyeWZD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPhyeWZD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPhyeWZD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPhyeWZD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPhyeWZD\App_KernelDevDebugContainer([
    'container.build_hash' => 'PhyeWZD',
    'container.build_id' => '1bad908a',
    'container.build_time' => 1673550856,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPhyeWZD');
